import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'np-bg': '#f0f0f0',
        'np-card': '#ffffff',
        'np-card-soft': '#f8f8f8',
        'np-card-off': '#f9f9f9',
        'np-footer': '#000000',
        'np-text': '#181818',
        'np-dark': '#121212',
        'np-muted': '#a9a9a9',
        'np-grey': '#7c7c7c',
        'np-eyebrow': 'rgb(201,197,197)',
        'np-border': '#d6d6d6',
        'np-border-dk': '#363636',
        'np-border-pill': '#181818',
        'np-green': '#1dcc5d',
        'np-green-trust': 'rgb(36,143,98)',
        'np-mark-green': 'rgb(206,232,204)',
        'np-mark-purple': 'rgb(219,204,232)',
        noprob: {
          bg: '#f0f0f0',
          card: '#ffffff',
          'card-soft': '#f8f8f8',
          'card-off': '#f9f9f9',
          footer: '#000000',
          text: '#181818',
          dark: '#121212',
          muted: '#a9a9a9',
          grey: '#7c7c7c',
          border: '#d6d6d6',
          'border-dk': '#363636',
          green: '#1dcc5d',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Inter Display"', 'Inter', 'sans-serif'],
        serif: ['"Source Serif 4"', 'Georgia', 'serif'],
      },
      fontSize: {
        'np-hero': ['3.8rem', { lineHeight: '1em', letterSpacing: '-0.05em', fontWeight: '600' }],
        'np-h2': ['3.5rem', { lineHeight: '1.2em', letterSpacing: '-0.07em', fontWeight: '600' }],
        'np-h2-md': ['2.24rem', { lineHeight: '1.2em', letterSpacing: '-0.05em' }],
        'np-h2-sm': ['2rem', { lineHeight: '1.2em', letterSpacing: '-0.07em', fontWeight: '600' }],
        'np-pricing': ['2.5rem', { lineHeight: '1.1em', letterSpacing: '-0.05em', fontWeight: '600' }],
        'np-footer': ['4rem', { lineHeight: '1em', letterSpacing: '-0.05em', fontWeight: '600' }],
        'np-body': ['1.125rem', { lineHeight: '1.4em', letterSpacing: '-0.02em', fontWeight: '500' }],
        'np-body-sm': ['0.9rem', { lineHeight: '1.6em', letterSpacing: '-0.02em', fontWeight: '500' }],
        'np-label': ['0.875rem', { lineHeight: '1.4em', letterSpacing: '-0.04em', fontWeight: '600' }],
        'np-tiny': ['0.75rem', { lineHeight: '1.2em', letterSpacing: '-0.04em', fontWeight: '500' }],
        'np-eyebrow': ['0.875rem', { lineHeight: '100%', letterSpacing: '-0.06em', fontWeight: '600' }],
        'np-price': ['1.8rem', { lineHeight: '1em', letterSpacing: '-0.04em', fontWeight: '700' }],
        'np-card-h': ['1.13rem', { lineHeight: '1.3em', letterSpacing: '-0.02em', fontWeight: '600' }],
        hero: ['3.8rem', { lineHeight: '1em', letterSpacing: '-0.05em', fontWeight: '600' }],
        'h2-xl': ['2.8rem', { lineHeight: '1.2em', letterSpacing: '-0.05em', fontWeight: '600' }],
        'h2-lg': ['2.25rem', { lineHeight: '1.2em', letterSpacing: '-0.07em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.4em', letterSpacing: '-0.02em' }],
        'body-sm': ['0.9rem', { lineHeight: '1.5em', letterSpacing: '-0.02em' }],
        label: ['0.875rem', { lineHeight: '1.4em', letterSpacing: '-0.04em' }],
        tiny: ['0.75rem', { lineHeight: '1.2em', letterSpacing: '-0.04em' }],
      },
      maxWidth: {
        noprob: '1200px',
        'noprob-sm': '1100px',
        'noprob-content': '800px',
      },
      borderRadius: {
        pill: '50px',
        card: '16px',
        'card-lg': '24px',
        'eyebrow-cat': '5px',
      },
      boxShadow: {
        card: `rgba(108, 113, 128, 0.08) 0px 2px 4px 0px,
               rgba(108, 113, 128, 0.07) 0px 7px 7px 0px,
               rgba(108, 113, 128, 0.04) 0px 17px 10px 0px,
               rgba(108, 113, 128, 0.01) 0px 29px 12px 0px,
               rgba(108, 113, 128, 0) 0px 46px 13px 0px`,
        btn: 'rgba(26, 26, 26, 0.25) 0px 0px 4px 2px',
        'pricing-inner': 'rgba(0, 0, 0, 0.25) 0px 1px 2px 0px inset',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-rev': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(48px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(-240deg)' },
          '50%': { transform: 'translateY(-12px) rotate(-240deg)' },
        },
        preloader: {
          '0%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { opacity: '0', pointerEvents: 'none' },
        },
        rotateSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        marquee: 'marquee 35s linear infinite',
        'marquee-rev': 'marquee-rev 35s linear infinite',
        float: 'float 6s ease-in-out infinite',
        'fade-up': 'fadeUp 0.6s ease forwards',
        preloader: 'preloader 1.5s ease forwards 0.5s',
        'rotate-slow': 'rotateSlow 30s linear infinite',
      },
    },
  },
  plugins: [],
}

export default config
